# PURL configuration for http://purl.obolibrary.org/obo/aism

idspace: AISM
base_url: /obo/aism

products:
- aism.owl: https://raw.githubusercontent.com/insect-morphology/aism/master/aism.owl
- aism.obo: https://raw.githubusercontent.com/insect-morphology/aism/master/aism.obo
- aism.json: https://raw.githubusercontent.com/insect-morphology/aism/master/aism.json

term_browser: ontobee
example_terms:
- AISM_0000005

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/insect-morphology/aism/v
  tests:
    - from: /releases/2021-04-26/
      to: https://raw.githubusercontent.com/insect-morphology/aism/v2021-04-26/

- prefix: /tracker/
  replacement: https://github.com/insect-morphology/aism/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/AISM?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/insect-morphology/aism/master/
