# PURL configuration for http://purl.obolibrary.org/obo/aro

idspace: ARO
base_url: /obo/aro

products:
- aro.owl: https://raw.githubusercontent.com/arpcard/aro/master/aro.owl
- aro.obo: https://raw.githubusercontent.com/arpcard/aro/master/src/ontology/aro.obo

term_browser: ontobee

entries:

- prefix: /tracker/
  replacement: https://github.com/arpcard/aro/issues

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/arpcard/aro/master/
