# PURL configuration for http://purl.obolibrary.org/obo/ato

idspace: ATO
base_url: /obo/ato

products:
- ato.owl: http://ontologies.berkeleybop.org/ato.owl
- ato.obo: http://ontologies.berkeleybop.org/ato.obo

term_browser: ontobee
example_terms:
- ATO_0000000
