# PURL configuration for http://purl.obolibrary.org/obo/bspo

idspace: BSPO
base_url: /obo/bspo

products:
- bspo.owl: https://raw.githubusercontent.com/obophenotype/biological-spatial-ontology/master/bspo.owl
- bspo.obo: https://raw.githubusercontent.com/obophenotype/biological-spatial-ontology/master/bspo.obo

term_browser: ontobee
example_terms:
- BSPO_0000000

entries:
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/biological-spatial-ontology/v
