# PURL configuration for http://purl.obolibrary.org/obo/cdao

idspace: CDAO
base_url: /obo/cdao

products:
- cdao.owl: https://raw.githubusercontent.com/evoinfo/cdao/master/cdao.owl

term_browser: ontobee
example_terms:
- CDAO_0000040

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=CDAO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/CDAO_0000040
    to: http://www.ontobee.org/browser/rdf.php?o=CDAO&iri=http://purl.obolibrary.org/obo/CDAO_0000040

- prefix: /1.0/
  replacement: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-1.0/OWL/
  tests:
  - from: /1.0/cdao.owl
    to: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-1.0/OWL/cdao.owl

- regex: ^/obo/cdao/(\d+-\d+-\d+)/(\S+)$
  replacement: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-$1/$2
  tests:
  - from: /2012-06-06/cdao.owl
    to: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-2012-06-06/cdao.owl
  - from: /2012-04-12/cdao.owl
    to: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-2012-04-12/cdao.owl
  - from: /2013-02-01/cdao.owl
    to: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-2013-02-01/cdao.owl
  - from: /2019-06-26/cdao.owl
    to: https://raw.githubusercontent.com/evoinfo/cdao/cdao-rel-2019-06-26/cdao.owl

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/evoinfo/cdao/master/
