# PURL configuration for http://purl.obolibrary.org/obo/cmo

idspace: CMO
base_url: /obo/cmo

products:
- cmo.owl: http://ontologies.berkeleybop.org/cmo.owl
- cmo.obo: http://ontologies.berkeleybop.org/cmo.obo

term_browser: ontobee
example_terms:
- CMO_0000000
