# PURL configuration for http://purl.obolibrary.org/obo/cro

idspace: CRO
base_url: /obo/cro

products:
- cro.owl: https://raw.githubusercontent.com/data2health/contributor-role-ontology/master/cro.owl
- cro.obo: https://raw.githubusercontent.com/data2health/contributor-role-ontology/master/cro.obo

term_browser: ontobee
example_terms:
- CRO_00000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/data2health/contributor-role-ontology/v

- prefix: /tracker/
  replacement: https://github.com/data2health/contributor-role-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/CRO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/data2health/contributor-role-ontology/master/
