# PURL configuration for http://purl.obolibrary.org/obo/ecocore

idspace: ECOCORE
base_url: /obo/ecocore

products:
- ecocore.owl: https://raw.githubusercontent.com/EcologicalSemantics/ecocore/master/ecocore.owl
- ecocore.obo: https://raw.githubusercontent.com/EcologicalSemantics/ecocore/master/ecocore.obo

term_browser: ontobee
example_terms:
- ECOCORE_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/EcologicalSemantics/ecocore/v

- prefix: /tracker/
  replacement: https://github.com/EcologicalSemantics/ecocore/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/ECOCORE?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/EcologicalSemantics/ecocore/master/
