# PURL configuration for http://purl.obolibrary.org/obo/ehda

idspace: EHDA
base_url: /obo/ehda

products:
- ehda.owl: http://ontologies.berkeleybop.org/ehda.owl
- ehda.obo: http://ontologies.berkeleybop.org/ehda.obo

term_browser: ontobee
example_terms:
- EHDA_1
