# PURL configuration for http://purl.obolibrary.org/obo/ehdaa

idspace: EHDAA
base_url: /obo/ehdaa

products:
- ehdaa.owl: http://ontologies.berkeleybop.org/ehdaa.owl
- ehdaa.obo: http://ontologies.berkeleybop.org/ehdaa.obo

term_browser: ontobee
example_terms:
- EHDAA_1
