# PURL configuration for http://purl.obolibrary.org/obo/emap

idspace: EMAP
base_url: /obo/emap

products:
- emap.owl: http://ontologies.berkeleybop.org/emap.owl

term_browser: ontobee
example_terms:
- EMAP_1
