# PURL configuration for http://purl.obolibrary.org/obo/eo

idspace: EO
base_url: /obo/eo

products:
- eo.owl: https://raw.githubusercontent.com/Planteome/plant-environment-ontology/master/plant-environment-ontology.obo.owl
- eo.OBO: https://raw.githubusercontent.com/Planteome/plant-environment-ontology/master/plant-environment-ontology.obo

term_browser: ontobee
example_terms:
- EO_0007359

entries:
- exact: /tracker
  replacement: https://github.com/Planteome/plant-environment-ontology/issues
