# PURL configuration for http://purl.obolibrary.org/obo/fbbi

idspace: FBbi
base_url: /obo/fbbi

products:
- fbbi.owl: https://raw.githubusercontent.com/Imaging-semantics/fbbi/master/fbbi.owl
- fbbi.obo: https://raw.githubusercontent.com/Imaging-semantics/fbbi/master/fbbi.obo

term_browser: ontobee
example_terms:
- FBbi_0000001
