# PURL configuration for http://purl.obolibrary.org/obo/fbbt

idspace: FBbt
base_url: /obo/fbbt

base_redirect:  https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki

products:
- fbbt.owl: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt.owl
- fbbt.obo: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt.obo
- FBbt_RO.owl: http://purl.obolibrary.org/obo/fbbt/2011-09-06/FBbt_helper_relations.owl
- fbbt.json: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt.json


term_browser: ontobee
example_terms:
- FBbt_10000000

entries:
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/v

- exact: /vfb/demo/owled2014_demo.owl.
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_papers/master/owl/owled2014_demo.owl

- exact: /tracker
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues

- exact: /downloads
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki/Download-guide

- prefix: /2011-09-06/
  replacement: http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/anatomy/gross_anatomy/animal_gross_anatomy/fly/2011-09-06/

- prefix: /2013-06-13/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2013-06-13/

- prefix: /2013-07-09/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2013-07-09/

- prefix: /2013-07-10/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2013-07-10/

- prefix: /2013-07-26/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2013-07-26/

- prefix: /2014-01-29/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2014-01-29/

- prefix: /2014-05-26/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2014-05-26/

- prefix: /2014-11-07/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2014-11-07/

- prefix: /2015-03-11/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2015-03-11/

- prefix: /2015-05-12/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2015-05-123/

- prefix: /2015-07-16/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2015-07-16/

- prefix: /2015-09-16/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2015-09-16/

- prefix: /2016-01-21/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2016-01-21/

- prefix: /2016-04-05/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2016-04-05/

- prefix: /2016-06-02/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2016-06-02/

- prefix: /2016-08-17/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2016-08-17/

- prefix: /2016-12-08/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2016-12-08/

- prefix: /2017-02-15/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2017-02-15/

- prefix: /2017-05-03/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2017-05-03/

- prefix: /2017-09-06/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2017-09-06/

- prefix: /2018-02-21/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2018-02-21/

- prefix: /2018-07-05/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2018-07-05/

- prefix: /2018-08-08/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2018-08-08/

- prefix: /2018-10-03/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2018-10-03/

- prefix: /2019-01-16/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2019-01-16/

- prefix: /2019-02-14/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2019-02-14/

- prefix: /2019-03-28/
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt/releases/2019-03-28/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=FBbt&iri=http://purl.obolibrary.org/obo/
  
- exact: /vfb/vfb.owl
  replacement: http://virtualflybrain.org/owl/vfb.owl
  
- regex: ^/obo/fbbt/vfb/releases/(.*)/vfb\.owl$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/$1/src/owl/vfb.owl.gz
  tests:
  - from: /vfb/releases/Current/vfb.owl
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Current/src/owl/vfb.owl.gz
    
- regex: ^/obo/fbbt/vfb/releases/(.*)/fbbt_(.*)\.owl$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/$1/src/owl/fbbt_$2.owl.gz
  tests:
  - from: /vfb/releases/Current/fbbt_vfb_ind.owl
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Current/src/owl/fbbt_vfb_ind.owl.gz
  
- regex: ^/obo/fbbt/vfb/releases/(.*)/$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/$1/src/owl/
  tests:
  - from: /vfb/releases/Current/
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Current/src/owl/
  
- regex: ^/obo/fbbt/vfb/(2016-0[0-6]-[0-9][0-9])/vfb\.owl$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/$1/vfb.owl.gz
  tests:
  - from: /vfb/2016-01-21/vfb.owl
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/2016-01-21/vfb.owl.gz
  
- regex: ^/obo/fbbt/vfb/(2016-0[0-6]-[0-9][0-9])/fbbt_(.*)\.owl$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/$1/fbbt_$2.owl
  tests:
  - from: /vfb/2016-01-21/fbbt_vfb_ind.owl
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/2016-01-21/fbbt_vfb_ind.owl
  
- regex: ^/obo/fbbt/vfb/(201[5-6]-0[0-6]-[0-9][0-9])/$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/$1/
  tests:
  - from: /vfb/2016-01-21/
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Archive/src/owl/2016-01-21/

- regex: ^/obo/fbbt/vfb/(20.*)/vfb\.owl$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/$1/src/owl/vfb.owl.gz
  tests:
  - from: /vfb/2016-07-12/vfb.owl
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/2016-07-12/src/owl/vfb.owl.gz

- regex: ^/obo/fbbt/vfb/(20.*)/$
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/$1/src/owl/
  tests:
  - from: /vfb/2016-07-12/
    to: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/2016-07-12/src/owl/

- prefix: /vfb/
  replacement: https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Current/src/owl/

- prefix: /wiki
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki

- prefix: /doc
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki

- prefix: /
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/

