# PURL configuration for http://purl.obolibrary.org/obo/fbsp

idspace: FBsp
base_url: /obo/fbsp

products:
- fbsp.owl: http://ontologies.berkeleybop.org/fbsp.owl
- fbsp.obo: http://ontologies.berkeleybop.org/fbsp.obo

term_browser: ontobee
example_terms:
- FBsp_00000000
