# PURL configuration for http://purl.obolibrary.org/obo/fma

idspace: FMA
base_url: /obo/fma

products:
- fma.owl: http://ontologies.berkeleybop.org/fma.owl
- fma.obo: http://ontologies.berkeleybop.org/fma.obo

term_browser: ontobee
example_terms:
- FMA_62955
