# PURL configuration for http://purl.obolibrary.org/obo/gecko

idspace: GECKO
base_url: /obo/gecko

products:
- gecko.owl: https://raw.githubusercontent.com/IHCC-cohorts/GECKO/master/gecko.owl

term_browser: ols
example_terms:
- GECKO_0000001

entries:
- exact: /ihcc-gecko.owl
  replacement: https://raw.githubusercontent.com/IHCC-cohorts/GECKO/master/views/ihcc-gecko.owl

- prefix: /views/
  replacement: https://raw.githubusercontent.com/IHCC-cohorts/GECKO/master/views/

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/IHCC-cohorts/GECKO/v
