# PURL configuration for http://purl.obolibrary.org/obo/hom

idspace: HOM
base_url: /obo/hom

products:
- hom.owl: http://ontologies.berkeleybop.org/hom.owl

term_browser: ontobee
example_terms:
- HOM_0000000
