# PURL configuration for http://purl.obolibrary.org/obo/hsapdv

idspace: HsapDv
base_url: /obo/hsapdv

products:
- hsapdv.owl: http://ontologies.berkeleybop.org/hsapdv.owl
- hsapdv.obo: http://ontologies.berkeleybop.org/hsapdv.obo

term_browser: ontobee
example_terms:
- HsapDv_0000000
