# PURL configuration for http://purl.obolibrary.org/obo/ico

idspace: ICO
base_url: /obo/ico

products:
- ico.owl: https://raw.githubusercontent.com/ICO-ontology/ICO/master/ico.owl

term_browser: ontobee
example_terms:
- ICO_0000001 
