# PURL configuration for http://purl.obolibrary.org/obo/ido

idspace: IDO
base_url: /obo/ido

base_redirect: http://infectiousdiseaseontology.org/page/Main_Page

products:
- ido.owl: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/2017-11-03/ido.owl
- ido.obo: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2014-08-01/ido.obo

term_browser: ontobee
example_terms:
- IDO_0000586

entries:
- exact: /
  replacement: http://www.infectiousdiseaseontology.org/

- exact: /owldoc
  replacement: http://owl.cs.manchester.ac.uk/browser/classes/211650690/?session=11d12f491be-6760-11d12f4b77a

- exact: /dev/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/trunk/src/ontology/ido-core/ido.owl

- exact: /2009-08-14/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2009-08-14/ido.owl

- exact: /dev/pathway-external.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/trunk/src/ontology/immunology/proto/pathway-external.owl

- exact: /dev/pathway-external-derived.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/trunk/src/ontology/immunology/proto/pathway-external-derived.owl

- exact: /dev/pathway-defs.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/trunk/src/ontology/immunology/proto/pathway-defs.owl

- exact: /tracker
  replacement: https://github.com/infectious-disease-ontology/infectious-disease-ontology/issues

- exact: /repository
  replacement: https://github.com/infectious-disease-ontology/infectious-disease-ontology

- exact: /2017-11-03/ido.owl  
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/2017-11-03/ido.owl
  
- exact: /2010-05-26/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-05-26/ido.owl

- exact: /2010-12-02/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/ido.owl

- exact: /2010-12-02/ido-base.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/ido-base.owl

- exact: /2010-12-02/ido-base-asserted.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-base-asserted.owl

- exact: /2010-12-02/ido-asserted.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-asserted.owl

- exact: /2010-12-02/ido-external.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-external.owl

- exact: /2010-12-02/ido-external-derived.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-external-derived.owl

- exact: /2010-12-02/ido-external-by-hand.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-external-by-hand.owl

- exact: /2010-12-02/ido-main-asserted.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-main-asserted.owl

- exact: /2010-12-02/ido-obsolete.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/asserted/ido-obsolete.owl

- exact: /2010-12-02/ido-main.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/ido-main.owl

- exact: /2010-12-02/ido.obo
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/ido.obo

- exact: /2010-05-26/ido.obo
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-05-26/ido.obo

- exact: /2010-12-02/ido-main-workaround.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/master/releases/2010-12-02/ido-main-workaround.owl

- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=IDO

- exact: /brucellosis.owl
  replacement: http://svn.code.sf.net/p/idobru/code/trunk/src/ontology/brucellosis.owl

- exact: /2014-08-01/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology-retired/master/releases/2014-08-01/ido_merged.owl

- exact: /2016-07-05/ido.owl
  replacement: https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology-retired/master/releases/2016-07-05/ido-merged.owl

- exact: /Sa.owl
  replacement: https://raw.githubusercontent.com/awqbi/ido-staph/master/releases/2012-06-22/ontology/Sa.owl

- exact: /2012-06-22/Sa.owl
  replacement: https://raw.githubusercontent.com/awqbi/ido-staph/master/releases/2012-06-22/ontology/Sa.owl

- exact: /Sa/dev/Sa.owl
  replacement: https://raw.githubusercontent.com/awqbi/ido-staph/master/src/ontology/Sa.owl

- exact: /Sa/narsa.owl
  replacement: https://raw.githubusercontent.com/awqbi/ido-staph/master/applications/narsa/narsa.owl

- exact: /Sa/narsa-isolates.owl
  replacement: https://raw.githubusercontent.com/awqbi/ido-staph/master/applications/narsa/narsa-isolates.owl

- prefix: /brucellosis/
  replacement: http://svn.code.sf.net/p/idobru/code/trunk/src/ontology/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=IDO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/IDO_0000586
    to: http://www.ontobee.org/browser/rdf.php?o=IDO&iri=http://purl.obolibrary.org/obo/IDO_0000586
