# PURL configuration for http://purl.obolibrary.org/obo/iev

idspace: IEV
base_url: /obo/iev

products:
- iev.owl: http://ontologies.berkeleybop.org/iev.owl
- iev.obo: http://ontologies.berkeleybop.org/iev.obo

term_browser: ontobee
example_terms:
- IEV_0000000
