# PURL configuration for http://purl.obolibrary.org/obo/mat

idspace: MAT
base_url: /obo/mat

products:
- mat.owl: http://ontologies.berkeleybop.org/mat.owl
- mat.obo: http://ontologies.berkeleybop.org/mat.obo

term_browser: ontobee
example_terms:
- MAT_0000000
