# PURL configuration for http://purl.obolibrary.org/obo/mi

idspace: MI
base_url: /obo/mi

products:
- mi.owl: http://ontologies.berkeleybop.org/mi.owl
- mi.obo: http://ontologies.berkeleybop.org/mi.obo

term_browser: ontobee
example_terms:
- MI_0346
