# PURL configuration for http://purl.obolibrary.org/obo/mmo

idspace: MMO
base_url: /obo/mmo

products:
- mmo.owl: http://ontologies.berkeleybop.org/mmo.owl
- mmo.obo: http://ontologies.berkeleybop.org/mmo.obo

term_browser: ontobee
example_terms:
- MMO_0000000
