# PURL configuration for http://purl.obolibrary.org/obo/mmusdv

idspace: MmusDv
base_url: /obo/mmusdv

products:
- mmusdv.owl: http://ontologies.berkeleybop.org/mmusdv.owl
- mmusdv.obo: http://ontologies.berkeleybop.org/mmusdv.obo

term_browser: ontobee
example_terms:
- MmusDv_0000000
