# PURL configuration for http://purl.obolibrary.org/obo/mod

idspace: MOD
base_url: /obo/mod

products:
- mod.owl: https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.owl
- mod.obo: https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.obo

term_browser: ontobee
example_terms:
- MOD_00000
