# PURL configuration for http://purl.obolibrary.org/obo/mop

idspace: MOP
base_url: /obo/mop

products:
- mop.owl: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/mop.owl
- mop.obo: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/mop.obo

term_browser: ontobee
example_terms:
- MOP_0000000
