# PURL configuration for http://purl.obolibrary.org/obo/

idspace: OBO
base_url: /obo

term_browser: custom


### Global Tests
tests:
# Test case insensitivity
- from: /chebi/about/CHEBI_15377
  to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377
- from: /CHEBI/about/CHEBI_15377
  to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377


### Entries
entries:


### Term Overrides

- exact: /BFO_0000050
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000050

- exact: /BFO_0000051
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000051

- exact: /BFO_0000066
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000066

- exact: /BFO_0000062
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000062


### Custom (non-Ontobee) term_browser redirects

# Term redirects for DUO
- regex: ^/obo/DUO_(\d+)$
  replacement: https://www.ebi.ac.uk/ols/ontologies/duo/terms?iri=http://purl.obolibrary.org/obo/DUO_$1
  status: see other
  tests:
  - from: /DUO_0000005
    to: https://www.ebi.ac.uk/ols/ontologies/duo/terms?iri=http://purl.obolibrary.org/obo/DUO_0000005

# Term redirects for MONDO
- regex: ^/obo/MONDO_(\d+)$
  replacement: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_$1
  status: see other
  tests:
  - from: /MONDO_0003847
    to: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0003847
    

# Term redirects for CHEBI
- regex: ^/obo/CHEBI_(\d+)$
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:$1
  status: see other
  tests:
  - from: /CHEBI_15377
    to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15377

# Term redirects for HP
- regex: ^/obo/HP_(\d+)$
  replacement: https://hpo.jax.org/app/browse/term/HP:$1
  status: see other
  tests:
  - from: /HP_0002088
    to: https://hpo.jax.org/app/browse/term/HP:0002088

# Term redirects for FLOPO
- regex: ^/obo/FLOPO_(\d+)$
  replacement: http://aber-owl.net/ontology/FLOPO#!http://purl.obolibrary.org/obo/FLOPO_$1
  status: see other
  tests:
  - from: /FLOPO_0000000
    to: http://aber-owl.net/ontology/FLOPO#!http://purl.obolibrary.org/obo/FLOPO_0000000
    
# Term redirects for HAO
- regex: ^/obo/HAO_(\d+)$
  replacement: http://api.hymao.org/api/ontology/ontology_class/HAO_$1
  status: see other
  tests:
  - from: /HAO_0000000
    to: http://api.hymao.org/api/ontology/ontology_class/HAO_0000000

# Term redirects for PR
# Match digits or UniProt ID, see http://www.uniprot.org/help/accession_numbers
- regex: ^/obo/PR_(\d+|[OPQ][0-9][A-Z0-9]{3}[0-9](-\d+)?|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}(-\d+)?)$
  replacement: https://proconsortium.org/cgi-bin/entry_pro?id=PR_$1
  status: see other
  tests:
  - from: /PR_000000001
    to: https://proconsortium.org/cgi-bin/entry_pro?id=PR_000000001
  - from: /PR_Q9BWV1
    to: https://proconsortium.org/cgi-bin/entry_pro?id=PR_Q9BWV1
  - from: /PR_P20263-1
    to: https://proconsortium.org/cgi-bin/entry_pro?id=PR_P20263-1
  - from: /PR_A0A0E0NEP8
    to: https://proconsortium.org/cgi-bin/entry_pro?id=PR_A0A0E0NEP8
  - from: /PR_A0A0E0NEP8-37
    to: https://proconsortium.org/cgi-bin/entry_pro?id=PR_A0A0E0NEP8-37
 
# Term redirects for GNO
# Match digits or GlyTouCan ID
- regex: ^/obo/GNO_(\d+|G[0-9]{5}[A-Z]{2})$
  replacement: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_$1
  status: see other
  tests:
  - from: /GNO_00000001
    to: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_00000001
  - from: /GNO_G00982CE
    to: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_G00982CE
    
# Term redirects for NCIT (not restricted to digits)
- regex: ^/obo/NCIT_([a-zA-Z0-9]+)$
  replacement: http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_$1
  status: see other
  tests:
  - from: /NCIT_C2916
    to: http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C2916

### OBO Format Specification
- exact: /oboformat/
  replacement: http://owlcollab.github.io/oboformat/doc/obo-syntax.html

- exact: /oboformat/spec.html
  replacement: http://owlcollab.github.io/oboformat/doc/obo-syntax.html
