# PURL configuration for http://purl.obolibrary.org/obo/ogi

idspace: OGI
base_url: /obo/ogi

products:
- ogi.owl: https://ontology-for-genetic-interval.googlecode.com/svn/trunk/src/OGI.owl

term_browser: ontobee
example_terms:
- OGI_0000002
