# PURL configuration for http://purl.obolibrary.org/obo/ohd

idspace: OHD
base_url: /obo/ohd

base_redirect: https://github.com/alanruttenberg/ohd-ontology

products:
- ohd.owl: https://raw.githubusercontent.com/alanruttenberg/ohd-ontology/master/src/ontology/ohd-2016-06-27-merged-inferred.owl

term_browser: ontobee
example_terms:
- OHD_0000019

entries:
- exact: /2016-06-27/ohd.owl
  replacement: https://raw.githubusercontent.com/alanruttenberg/ohd-ontology/master/src/ontology/ohd-2016-06-27-merged-inferred.owl

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OHD&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/OHD_0000019
    to: http://www.ontobee.org/browser/rdf.php?o=OHD&iri=http://purl.obolibrary.org/obo/OHD_0000019

- prefix: /dev/
  replacement: https://raw.githubusercontent.com/alanruttenberg/ohd-ontology/master/src/ontology/
