# PURL configuration for http://purl.obolibrary.org/obo/olatdv

idspace: OlatDv
base_url: /obo/olatdv

products:
- olatdv.owl: http://ontologies.berkeleybop.org/olatdv.owl
- olatdv.obo: http://ontologies.berkeleybop.org/olatdv.obo

term_browser: ontobee
example_terms:
- OlatDv_0000020
