# PURL configuration for http://purl.obolibrary.org/obo/ontoneo/

idspace: ONTONEO
base_url: /obo/ontoneo

products:
- ontoneo.owl: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/ontoneo.owl

term_browser: ontobee
example_terms:
- ONTONEO_00000005

entries:

### Project Page and Tracker
- exact: /project
  replacement: https://github.com/ontoneo-project/Ontoneo
 
- exact: /tracker
  replacement: https://github.com/ontoneo-project/Ontoneo/issues

### Imported ontologies current release
- prefix: /import/
  replacement: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/import/
  tests:
  - from: /import/ro_import.owl
    to: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/import/ro_import.owl

### Previous release

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/releases/
  tests:
  - from: /releases/2021-02-24/ontoneo.owl
    to: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/releases/2021-02-24/ontoneo.owl
  - from: /releases/2016-12-14/import/bfo_import.owl
    to: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/releases/2016-12-14/import/bfo_import.owl
  
### Documentation Pages and Redirects
- exact: /homepage
  replacement: http://ontoneo.com
