# PURL configuration for http://purl.obolibrary.org/obo/ovae

idspace: OVAE
base_url: /obo/ovae

products:
- ovae.owl: https://raw.githubusercontent.com/OVAE-Ontology/ovae/master/src/ontology/ovae_merged.owl

term_browser: ontobee
example_terms:
- OVAE_0000001
- OVAE_0000002
- OVAE_0000061
- OVAE_0000984

