# PURL configuration for http://purl.obolibrary.org/obo/pato

idspace: PATO
base_url: /obo/pato

base_redirect: https://github.com/pato-ontology/pato

products:
- pato.owl: https://raw.githubusercontent.com/pato-ontology/pato/master/pato.owl
- pato.obo: https://raw.githubusercontent.com/pato-ontology/pato/master/pato.obo
- pato.json: https://raw.githubusercontent.com/pato-ontology/pato/master/pato.json

term_browser: ontobee
example_terms:
- PATO_0000001

entries:
- exact: /tracker
  replacement: https://github.com/pato-ontology/pato/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/pato-ontology/pato/v

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=PATO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/PATO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=PATO&iri=http://purl.obolibrary.org/obo/PATO_0000001

- prefix: /subsets/
  replacement: https://raw.githubusercontent.com/pato-ontology/pato/master/subsets/

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/pato-ontology/pato/master/imports/

- exact: /
  replacement: https://github.com/pato-ontology/pato/
