# PURL configuration for http://purl.obolibrary.org/obo/pco

idspace: PCO
base_url: /obo/pco

products:
- pco.owl:  https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/pco.owl
- pco.obo: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/pco.obo

term_browser: ontobee
example_terms:
- PCO_0000000

entries:
- exact: /releases/2021-05-03/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2021-05-03/pco.owl

# Handle typo in versionIRI date, see https://github.com/PopulationAndCommunityOntology/pco/issues/84
- exact: /releases/2020-02-13/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-02-12/pco.owl

- exact: /releases/2016-12-14/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2016-12-14/src/ontology/pco_merged_inferred.owl

- exact: /releases/2016-08-01/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2016-08-01/src/ontology/pco_merged_inferred.owl

- exact: /pco_merged_inferred.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/src/ontology/pco_merged_inferred.owl
   
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/
  tests:
  - from: /releases/2020-08-26/pco.owl
    to: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-08-26/pco.owl
  - from: /releases/2017-08-16/pco.owl
    to: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2017-08-16/pco.owl
  - from: /releases/2017-11-06/pco.owl
    to: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2017-11-06/pco.owl

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/PCO?iri=http://purl.obolibrary.org/obo/
  
- prefix: /tracker/
  replacement: https://github.com/PopulationAndCommunityOntology/pco/issues

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/
