# PURL configuration for http://purl.obolibrary.org/obo/pdro

idspace: PDRO
base_url: /obo/pdro

products:
- pdro.owl: https://raw.githubusercontent.com/OpenLHS/PDRO/master/pdro.owl

term_browser: ontobee
example_terms:
- PDRO_0000007
