# PURL configuration for http://purl.obolibrary.org/obo/peco

idspace: PECO
base_url: /obo/peco

products:
- peco.owl: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/master/peco.owl
- peco.OBO: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/master/peco.obo

term_browser: ontobee
example_terms:
- PECO_0007359

entries:
- prefix: /subsets/
  replacement: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/master/subsets/
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/master/imports/  
- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/master/src/ontology/patterns/  
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/Planteome/plant-experimental-conditions-ontology/v
- exact: /tracker
  replacement: https://github.com/Planteome/plant-experimental-conditions-ontology/issues
