# PURL configuration for http://purl.obolibrary.org/obo/pw

idspace: PW
base_url: /obo/pw

products:
- pw.owl: http://ontologies.berkeleybop.org/pw.owl
- pw.obo: http://ontologies.berkeleybop.org/pw.obo

term_browser: ontobee
example_terms:
- PW_0000555
