# PURL configuration for http://purl.obolibrary.org/obo/rbo

idspace: RBO
base_url: /obo/rbo

products:
- rbo.owl: https://raw.githubusercontent.com/DanBerrios/RBO/master/rbo.owl
- rbo.obo: https://raw.githubusercontent.com/DanBerrios/RBO/master/rbo.obo

term_browser: ontobee
example_terms:
- RBO_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/DanBerrios/RBO/v

- prefix: /tracker/
  replacement: https://github.com/DanBerrios/RBO/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/RBO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/DanBerrios/RBO/master/
