# PURL configuration for http://purl.obolibrary.org/obo/rxno

idspace: RXNO
base_url: /obo/rxno

products:
- rxno.owl: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.owl
- rxno.obo: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.obo

term_browser: ontobee
example_terms:
- RXNO_0000000
