# PURL configuration for http://purl.obolibrary.org/obo/scdo

idspace: SCDO
base_url: /obo/scdo

products:
- scdo.owl: https://raw.githubusercontent.com/scdodev/scdo-ontology/master/scdo.owl
- scdo.obo: https://raw.githubusercontent.com/scdodev/scdo-ontology/master/scdo.obo

term_browser: ontobee
example_terms:
- SCDO_0000204

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/scdodev/scdo-ontology/v

- prefix: /tracker/
  replacement: https://github.com/scdodev/scdo-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/SCDO?iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://raw.githubusercontent.com/scdodev/scdo-ontology/master/
