# PURL configuration for http://purl.obolibrary.org/obo/tgma

idspace: TGMA
base_url: /obo/tgma

products:
- tgma.owl: https://raw.githubusercontent.com/VEuPathDB-ontology/TGMA/v2013-06-03/tgma.owl
- tgma.obo: https://raw.githubusercontent.com/VEuPathDB-ontology/TGMA/v2013-06-03/tgma.obo

term_browser: ontobee
example_terms:
- TGMA_0000000

entries:
- exact: /releases/2013-06-03/tgma.owl
  replacement: https://raw.githubusercontent.com/VEuPathDB-ontology/TGMA/v2013-06-03/tgma.owl
