# PURL configuration for http://purl.obolibrary.org/obo/tto

idspace: TTO
base_url: /obo/tto

products:
- tto.owl: https://raw.githubusercontent.com/phenoscape/teleost-taxonomy-ontology/master/tto.owl
- tto.obo: https://raw.githubusercontent.com/phenoscape/teleost-taxonomy-ontology/master/tto.obo

term_browser: ontobee
example_terms:
- TTO_201
