# PURL configuration for http://purl.obolibrary.org/obo/vhog

idspace: VHOG
base_url: /obo/vhog

products:
- vhog.owl: http://ontologies.berkeleybop.org/vhog.owl
- vhog.obo: http://ontologies.berkeleybop.org/vhog.obo

term_browser: ontobee
example_terms:
- VHOG_0001533
