# PURL configuration for http://purl.obolibrary.org/obo/xao

idspace: XAO
base_url: /obo/xao

products:
- xao.owl: https://raw.githubusercontent.com/xenopus-anatomy/xao/master/xenopus_anatomy.owl
- xao.obo: https://raw.githubusercontent.com/xenopus-anatomy/xao/master/xenopus_anatomy.obo

term_browser: ontobee

entries:
- prefix: /tracker/
  replacement: https://github.com/xenopus-anatomy/xao/issues
