# PURL configuration for http://purl.obolibrary.org/obo/xco

idspace: XCO
base_url: /obo/xco

products:
- xco.owl: http://ontologies.berkeleybop.org/xco.owl
- xco.obo: http://ontologies.berkeleybop.org/xco.obo

term_browser: ontobee
example_terms:
- XCO_0000000
