# PURL configuration for http://purl.obolibrary.org/obo/zfs

idspace: ZFS
base_url: /obo/zfs

products:
- zfs.owl: http://ontologies.berkeleybop.org/zfs.owl
- zfs.obo: http://ontologies.berkeleybop.org/zfs.obo

term_browser: ontobee
example_terms:
- ZFS_0100000
