name: Purl GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DockertTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: false 
          tags: purl:latest

      - name: Run Tests 
        run: |
          # docker run --rm -w /var/www/hello-world-docker-action -t purl:latest ls -l 
          # docker run -w /var/www/hello-world-docker-action -t purl:latest sudo make all test
          docker run -w /var/www/hello-world-docker-action -t purl:latest git name-rev --name-only HEAD
          docker run -w /var/www/hello-world-docker-action -t purl:latest git rev-parse main
          docker run -w /var/www/hello-world-docker-action -t purl:latest sudo make all test

